import { TemplateConfig } from '../types/ExcelTemplateTypes';

export const ENTITY_TEMPLATES: Record<string, TemplateConfig> = {
  cliente: {
    entityType: 'cliente',
    entityName: 'Clientes',
    includeExamples: true,
    includeValidation: true,
    includeInstructions: true,
    includeReferenceData: false,
    fields: [
      {
        key: 'nombre',
        label: 'Nombre*',
        required: true,
        type: 'text',
        description: 'Razón social o nombre comercial del cliente',
        example: 'Empresa Transportes ABC S.A.',
        validation: 'Mínimo 2 caracteres, máximo 100',
      },
      {
        key: 'cuit',
        label: 'CUIT*',
        required: true,
        type: 'text',
        description: 'CUIT sin guiones ni espacios',
        example: '20123456789',
        validation: 'Formato: 11 dígitos',
      },
      {
        key: 'email',
        label: 'Email',
        required: false,
        type: 'text',
        description: 'Correo electrónico de contacto',
        example: 'contacto@empresa.com',
        validation: 'Formato de email válido',
      },
      {
        key: 'telefono',
        label: 'Teléfono',
        required: false,
        type: 'text',
        description: 'Número de teléfono',
        example: '+54 11 1234-5678',
      },
      {
        key: 'direccion',
        label: 'Dirección',
        required: false,
        type: 'text',
        description: 'Dirección fiscal',
        example: 'Av. Corrientes 1234, CABA',
      },
      {
        key: 'activo',
        label: 'Activo',
        required: false,
        type: 'boolean',
        description: 'Estado del cliente (VERDADERO/FALSO)',
        example: 'VERDADERO',
        validation: 'VERDADERO o FALSO',
      },
    ],
  },
  empresa: {
    entityType: 'empresa',
    entityName: 'Empresas',
    includeExamples: true,
    includeValidation: true,
    includeInstructions: true,
    includeReferenceData: false,
    fields: [
      {
        key: 'nombre',
        label: 'Nombre*',
        required: true,
        type: 'text',
        description: 'Nombre de la empresa',
        example: 'Transportes del Sur',
      },
      {
        key: 'tipo',
        label: 'Tipo*',
        required: true,
        type: 'select',
        options: ['Propia', 'Subcontratada'],
        description: 'Tipo de empresa',
        example: 'Propia',
      },
      {
        key: 'cuit',
        label: 'CUIT*',
        required: true,
        type: 'text',
        description: 'CUIT de la empresa',
        example: '30123456789',
      },
      {
        key: 'telefono',
        label: 'Teléfono',
        required: false,
        type: 'text',
        description: 'Teléfono de contacto',
        example: '+54 11 1234-5678',
      },
      {
        key: 'email',
        label: 'Email',
        required: false,
        type: 'text',
        description: 'Email de contacto',
        example: 'info@empresa.com',
      },
    ],
  },
  personal: {
    entityType: 'personal',
    entityName: 'Personal',
    includeExamples: true,
    includeValidation: true,
    includeInstructions: true,
    includeReferenceData: true,
    fields: [
      {
        key: 'nombre',
        label: 'Nombre*',
        required: true,
        type: 'text',
        description: 'Nombre completo',
        example: 'Juan Carlos Pérez',
      },
      {
        key: 'dni',
        label: 'DNI*',
        required: true,
        type: 'text',
        description: 'Documento Nacional de Identidad',
        example: '12345678',
      },
      {
        key: 'tipoPersonal',
        label: 'Tipo Personal*',
        required: true,
        type: 'select',
        options: ['Conductor', 'Ayudante', 'Administrativo', 'Mantenimiento'],
        description: 'Tipo de personal',
        example: 'Conductor',
      },
      {
        key: 'empresaId',
        label: 'ID Empresa*',
        required: true,
        type: 'text',
        description: 'ID de la empresa (ver hoja Referencias)',
        example: '507f1f77bcf86cd799439011',
      },
      {
        key: 'telefono',
        label: 'Teléfono',
        required: false,
        type: 'text',
        description: 'Teléfono de contacto',
        example: '+54 11 9876-5432',
      },
      {
        key: 'email',
        label: 'Email',
        required: false,
        type: 'text',
        description: 'Email personal',
        example: 'juan.perez@email.com',
      },
    ],
  },
  sites: {
    entityType: 'sites',
    entityName: 'Sites',
    includeExamples: true,
    includeValidation: true,
    includeInstructions: true,
    includeReferenceData: true,
    fields: [
      {
        key: 'nombre',
        label: 'Nombre *',
        required: true,
        type: 'text',
        description: 'Nombre del sitio',
        example: 'Almacén Central',
        validation: 'Mínimo 2 caracteres, único por cliente',
      },
      {
        key: 'cliente',
        label: 'Cliente *',
        required: true,
        type: 'text',
        description: 'Nombre del cliente (debe existir en el sistema)',
        example: 'Empresa Ejemplo S.A.C.',
      },
      {
        key: 'codigo',
        label: 'Código',
        required: false,
        type: 'text',
        description: 'Código identificador único por cliente',
        example: 'ALM001',
      },
      {
        key: 'direccion',
        label: 'Dirección',
        required: false,
        type: 'text',
        description: 'Dirección completa del sitio',
        example: 'Av. Industrial 123, Buenos Aires',
      },
      {
        key: 'localidad',
        label: 'Localidad',
        required: false,
        type: 'text',
        description: 'Ciudad o localidad',
        example: 'Capital Federal',
      },
      {
        key: 'provincia',
        label: 'Provincia',
        required: false,
        type: 'text',
        description: 'Provincia o estado',
        example: 'Buenos Aires',
      },
      {
        key: 'longitud',
        label: 'Longitud',
        required: false,
        type: 'number',
        description: 'Coordenada GPS (-180 a 180)',
        example: '-58.3816',
      },
      {
        key: 'latitud',
        label: 'Latitud',
        required: false,
        type: 'number',
        description: 'Coordenada GPS (-90 a 90)',
        example: '-34.6037',
      },
    ],
  },
};
