declare module '@tabler/icons-react' {
  import { FC, SVGProps } from 'react';
  
  interface IconProps extends SVGProps<SVGSVGElement> {
    size?: number | string;
    stroke?: number;
  }
  
  // Definir todos los iconos como un tipo genérico
  // Esto permite cualquier icono que comience con "Icon"
  const TablerIcon: FC<IconProps>;
  
  // Iconos específicos que ya están en uso
  export const IconAlertCircle: FC<IconProps>;
  export const IconAlertTriangle: FC<IconProps>;
  export const IconArchive: FC<IconProps>;
  export const IconArrowLeft: FC<IconProps>;
  export const IconArrowRight: FC<IconProps>;
  export const IconArrowUp: FC<IconProps>;
  export const IconArrowDown: FC<IconProps>;
  export const IconBell: FC<IconProps>;
  export const IconBellOff: FC<IconProps>;
  export const IconBox: FC<IconProps>;
  export const IconBug: FC<IconProps>;
  export const IconBuilding: FC<IconProps>;
  export const IconBulb: FC<IconProps>;
  export const IconCalculator: FC<IconProps>;
  export const IconCalendar: FC<IconProps>;
  export const IconCalendarEvent: FC<IconProps>;
  export const IconCalendarStats: FC<IconProps>;
  export const IconCash: FC<IconProps>;
  export const IconCheck: FC<IconProps>;
  export const IconCheckupList: FC<IconProps>;
  export const IconChevronDown: FC<IconProps>;
  export const IconChevronLeft: FC<IconProps>;
  export const IconChevronRight: FC<IconProps>;
  export const IconChevronUp: FC<IconProps>;
  export const IconClearAll: FC<IconProps>;
  export const IconClipboardList: FC<IconProps>;
  export const IconClock: FC<IconProps>;
  export const IconClockHour12: FC<IconProps>;
  export const IconCloudUpload: FC<IconProps>;
  export const IconCode: FC<IconProps>;
  export const IconCoin: FC<IconProps>;
  export const IconColumns: FC<IconProps>;
  export const IconCopy: FC<IconProps>;
  export const IconCreditCard: FC<IconProps>;
  export const IconCrosshair: FC<IconProps>;
  export const IconCurrency: FC<IconProps>;
  export const IconCurrencyDollar: FC<IconProps>;
  export const IconCurrentLocation: FC<IconProps>;
  export const IconDashboard: FC<IconProps>;
  export const IconDatabase: FC<IconProps>;
  export const IconDeviceFloppy: FC<IconProps>;
  export const IconDots: FC<IconProps>;
  export const IconDownload: FC<IconProps>;
  export const IconEdit: FC<IconProps>;
  export const IconExclamationCircle: FC<IconProps>;
  export const IconExclamationMark: FC<IconProps>;
  export const IconExternalLink: FC<IconProps>;
  export const IconEye: FC<IconProps>;
  export const IconEyeOff: FC<IconProps>;
  export const IconFile: FC<IconProps>;
  export const IconFileAlert: FC<IconProps>;
  export const IconFileAnalytics: FC<IconProps>;
  export const IconFileExport: FC<IconProps>;
  export const IconFileImport: FC<IconProps>;
  export const IconFileInvoice: FC<IconProps>;
  export const IconFileReport: FC<IconProps>;
  export const IconFileSpreadsheet: FC<IconProps>;
  export const IconFileText: FC<IconProps>;
  export const IconFileTypeCsv: FC<IconProps>;
  export const IconFileTypePdf: FC<IconProps>;
  export const IconFileX: FC<IconProps>;
  export const IconFilter: FC<IconProps>;
  export const IconFingerprint: FC<IconProps>;
  export const IconFlag: FC<IconProps>;
  export const IconFunction: FC<IconProps>;
  export const IconGasStation: FC<IconProps>;
  export const IconGitMerge: FC<IconProps>;
  export const IconGraph: FC<IconProps>;
  export const IconHelp: FC<IconProps>;
  export const IconHistory: FC<IconProps>;
  export const IconId: FC<IconProps>;
  export const IconInfoCircle: FC<IconProps>;
  export const IconLayoutGrid: FC<IconProps>;
  export const IconLicense: FC<IconProps>;
  export const IconLink: FC<IconProps>;
  export const IconList: FC<IconProps>;
  export const IconListCheck: FC<IconProps>;
  export const IconLock: FC<IconProps>;
  export const IconLockOpen: FC<IconProps>;
  export const IconLogin: FC<IconProps>;
  export const IconLogout: FC<IconProps>;
  export const IconMail: FC<IconProps>;
  export const IconMap: FC<IconProps>;
  export const IconMap2: FC<IconProps>;
  export const IconMapPin: FC<IconProps>;
  export const IconMapSearch: FC<IconProps>;
  export const IconMath: FC<IconProps>;
  export const IconMathFunction: FC<IconProps>;
  export const IconMaximize: FC<IconProps>;
  export const IconMinimize: FC<IconProps>;
  export const IconMinus: FC<IconProps>;
  export const IconMoon: FC<IconProps>;
  export const IconNavigation: FC<IconProps>;
  export const IconNote: FC<IconProps>;
  export const IconPackage: FC<IconProps>;
  export const IconPercentage: FC<IconProps>;
  export const IconPhone: FC<IconProps>;
  export const IconPhoto: FC<IconProps>;
  export const IconPlayerPause: FC<IconProps>;
  export const IconPlayerPlay: FC<IconProps>;
  export const IconPlus: FC<IconProps>;
  export const IconPrinter: FC<IconProps>;
  export const IconReceipt: FC<IconProps>;
  export const IconRefresh: FC<IconProps>;
  export const IconReportAnalytics: FC<IconProps>;
  export const IconRestore: FC<IconProps>;
  export const IconRoad: FC<IconProps>;
  export const IconRoute: FC<IconProps>;
  export const IconRuler: FC<IconProps>;
  export const IconScale: FC<IconProps>;
  export const IconSchool: FC<IconProps>;
  export const IconSearch: FC<IconProps>;
  export const IconSelector: FC<IconProps>;
  export const IconSettings: FC<IconProps>;
  export const IconShare: FC<IconProps>;
  export const IconShieldCheck: FC<IconProps>;
  export const IconSortAscending: FC<IconProps>;
  export const IconSortDescending: FC<IconProps>;
  export const IconStethoscope: FC<IconProps>;
  export const IconSun: FC<IconProps>;
  export const IconTable: FC<IconProps>;
  export const IconTarget: FC<IconProps>;
  export const IconTemplate: FC<IconProps>;
  export const IconTrash: FC<IconProps>;
  export const IconTrendingDown: FC<IconProps>;
  export const IconTrendingUp: FC<IconProps>;
  export const IconTruck: FC<IconProps>;
  export const IconTruckDelivery: FC<IconProps>;
  export const IconUpload: FC<IconProps>;
  export const IconUser: FC<IconProps>;
  export const IconUserCheck: FC<IconProps>;
  export const IconUserPlus: FC<IconProps>;
  export const IconUsers: FC<IconProps>;
  export const IconVariable: FC<IconProps>;
  export const IconWand: FC<IconProps>;
  export const IconWeight: FC<IconProps>;
  export const IconWorld: FC<IconProps>;
  export const IconX: FC<IconProps>;
  export const IconChartBar: FC<IconProps>;
  export const IconClipboard: FC<IconProps>;
  export const IconFileCheck: FC<IconProps>;
  export const IconFileTypeXls: FC<IconProps>;
  export const IconFileUpload: FC<IconProps>;
  export const IconPalette: FC<IconProps>;
  export const IconTableExport: FC<IconProps>;
  export const IconTableImport: FC<IconProps>;
  
  // Exportar todos los iconos como default también
  const TablerIcons: {
    [key: string]: FC<IconProps>;
  };
  
  export default TablerIcons;
}