/**
 * Constantes compartidas para plantillas Excel
 * Archivo separado para evitar importaciones circulares
 */
export const EXCEL_SHARED_CONSTANTS = {
  COLUMN_WIDTHS: {
    INSTRUCTIONS_WIDE: 70,
    INSTRUCTIONS_STANDARD: 60,
    ID_COLUMN: 25,
    NAME_COLUMN: 40,
    STANDARD_COLUMN: 15,
    STATE_COLUMN: 10,
    SEPARATOR: 2,
  },
  PERSONAL: {
    TIPOS: {
      CONDUCTOR: 'Conductor',
      ADMINISTRATIVO: 'Administrativo',
      MECANICO: 'Mecánico',
      SUPERVISOR: 'Supervisor',
      OTRO: 'Otro',
    },
    BOOLEAN: {
      SI: 'Sí',
      NO: 'No',
    },
    HEADERS: [
      // Datos básicos
      'Nombre (*)',
      'Apellido (*)',
      'DNI (*)',
      'CUIL',
      'Tipo (*)',
      'Fecha Nacimiento',
      'Empresa (*)',
      'N° Legajo',
      'Fecha Ingreso',

      // Dirección
      'Dirección - Calle',
      'Dirección - Número',
      'Dirección - Localidad',
      'Dirección - Provincia',
      'Dirección - Código Postal',

      // Contacto
      'Teléfono',
      'Teléfono Emergencia',
      'Email',

      // Documentación - Licencia
      'Licencia - Número',
      'Licencia - Categoría',
      'Licencia - Vencimiento',

      // Documentación - Carnet Profesional
      'Carnet Prof. - Número',
      'Carnet Prof. - Vencimiento',

      // Documentación - Evaluaciones
      'Eval. Médica - Fecha',
      'Eval. Médica - Vencimiento',
      'Psicofísico - Fecha',
      'Psicofísico - Vencimiento',

      // Datos laborales
      'Categoría',
      'Obra Social',
      'ART',
      'Activo',
      'Observaciones',
    ],
    COLUMN_WIDTHS: {
      NOMBRE: 15,
      APELLIDO: 15,
      DNI: 12,
      CUIL: 15,
      TIPO: 15,
      FECHA_NAC: 12,
      EMPRESA: 20,
      LEGAJO: 10,
      FECHA_INGRESO: 12,
      DIR_CALLE: 20,
      DIR_NUMERO: 8,
      DIR_LOCALIDAD: 15,
      DIR_PROVINCIA: 15,
      DIR_CP: 10,
      TELEFONO: 15,
      TEL_EMERGENCIA: 15,
      EMAIL: 25,
      LIC_NUMERO: 15,
      LIC_CATEGORIA: 10,
      LIC_VENC: 12,
      CARNET_NUMERO: 15,
      CARNET_VENC: 12,
      EVAL_MED_FECHA: 12,
      EVAL_MED_VENC: 12,
      PSICO_FECHA: 12,
      PSICO_VENC: 12,
      CATEGORIA: 15,
      OBRA_SOCIAL: 15,
      ART: 15,
      ACTIVO: 8,
      OBSERVACIONES: 30,
    },
    INSTRUCTIONS: [
      ['PLANTILLA PARA CARGA MASIVA DE PERSONAL'],
      [''],
      ['INSTRUCCIONES DE USO:'],
      [''],
      ['1. Complete la información en la hoja "Personal"'],
      ['2. Los campos marcados con (*) son obligatorios'],
      ['3. Formatos requeridos:'],
      ['   - DNI: Solo números, 7-8 dígitos'],
      ['   - CUIL: Formato XX-XXXXXXXX-X'],
      ['   - Fechas: DD/MM/AAAA'],
      ['   - Email: Formato válido de correo'],
      ['   - Tipo: Seleccione del menú desplegable'],
      ['   - Empresa: Seleccione del menú (ver hoja Ref_Empresas)'],
      [''],
      ['TIPOS DE PERSONAL:'],
      ['- Conductor: Personal autorizado para manejar vehículos'],
      ['- Administrativo: Personal de oficina y gestión'],
      ['- Mecánico: Personal de mantenimiento'],
      ['- Supervisor: Personal de supervisión y control'],
      ['- Otro: Otros tipos no especificados'],
      [''],
      ['DOCUMENTACIÓN REQUERIDA PARA CONDUCTORES:'],
      ['- Licencia de Conducir: Obligatoria para tipo "Conductor"'],
      ['- Carnet Profesional: Requerido para transporte comercial'],
      ['- Evaluación Médica: Renovación anual obligatoria'],
      ['- Psicofísico: Evaluación psicológica anual'],
      [''],
      ['VALIDACIONES:'],
      ['- El DNI debe ser único en el sistema'],
      ['- La empresa debe existir en el sistema'],
      ['- El número de legajo debe ser único por empresa'],
      ['- Las fechas de vencimiento deben ser futuras'],
      ['- Para conductores, la licencia es obligatoria'],
      [''],
      ['NOTAS IMPORTANTES:'],
      ['- Elimine las filas de ejemplo antes de cargar'],
      ['- El sistema generará legajos automáticamente si no se especifican'],
      ['- Verifique las fechas de vencimiento de documentos'],
      ['- Para personal nuevo, la fecha de ingreso es obligatoria'],
      ['- Use la hoja "Ref_Empresas" para ver empresas disponibles'],
      [''],
      ['CAMPOS OBLIGATORIOS (*)'],
      ['- Nombre: Nombre de pila'],
      ['- Apellido: Apellido completo'],
      ['- DNI: Documento Nacional de Identidad'],
      ['- Tipo: Clasificación del personal'],
      ['- Empresa: Empresa a la que pertenece'],
    ],
  },
};
